version: '3'

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_DATABASE=pastebucket
        volumes:
            - mongo-data:/data/db
        network_mode: "host"
    api:
        build: ./api/
        depends_on:
            - mongo
        ports:
            - "49610:8080"

volumes:
  mongo-data: